site_name: DocForensics
site_description: Document Forensics Solution Documentation
site_author: Nivratti Boyane

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate

nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - User Guide: user_guide.md
    - Input Image Requirements: input_image_requirements.md
    - Features: features.md
    - API Documentation: api_documentation.md
    - Dataset Composition: dataset_composition.md
    - Understanding Document Forensics Workflow: understanding_document_forensics_workflow.md
    - Challenges: challenges.md
    - Release Notes: release_notes.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - glightbox
